language: shell
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: c0ulnShQRSAtDLyYnkuC8IktZs44dmewWzkFrN7RGjPYUscG6rc6dK6RQDnhbCtJQM+f5CR5U88WG8Eh0ToGM0GFzy34GJ0W5qtD6ZUp5s4CYxBbY8chYARSAxyi6mLhtVuym9AC+13MMbRhYDq/eMPsBHVTW9vAuxawTAdujk3T4mnIpxD11zEIr5xI0k7KV4b03UAoubUm9CXsiq8Qjoz4mc9mUUaI6FkSA3NNWSVZEaidHxasJCEb5opFRGhfk8sOBmLux1j/Ud2z42XwvNYYkRgLDSkyW12omos6F+7qKBV2hxvoOKFYCzS/QK/JCNNtrQiD8zAH4nAIB3g3MKjX1Hkoc8UgOaZOJImjoA/1rQDLh3V8drb0WCwQISXRuwY7BPCUgK1YxzutgjpnpUcJElDx3yhf4ee/HAmZzJbM2xhZhGscDNCp89U/ugLZ3xLX5NPeeCDrfVS3sIkeEhXC0UQjOYF9I/GVKo8oUsoASw41quHQ1lXlKha4qK7om5bvTc94SC9ZvcFFtli1f0VUDA5m+2ygatZk3il9DPkNWCMwpQnucFETYlFNaeGyjglNJLp3PhgwsQwMmCtsOK5XU36FcRfmQVkx2PR10AvjGuR1x3GL/dUtUPI9t85GMgbcFnw12oAkpdzETBRTnRdtGnrYFmWJ9uwnWSVbArw=

  bucket: control.octoblu.com
  endpoint: control.octoblu.com.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  on:
    branch: master
